### ISSUE TITLE
Please Provide the version of Keras and Theano

### ISSUE THREAD

**Issue by tracyliang18** [naamahadad/A-Two-Step-Disentanglement-Method#1]
[14:57:31] liangjiajun@rocket ~/workspace/research-2018/disentangle/A-Two-Step-Disentanglement-Method %% pip2 freeze | grep -e Keras -e Theano
The directory '/home/liangjiajun/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Keras==2.2.0
Keras-Applications==1.0.2
Keras-Preprocessing==1.0.1
Theano==1.0.2

I get the following error:
/home/liangjiajun/.local/lib/python2.7/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype
(float).type`.
  from ._conv import register_converters as _register_converters
Using Theano backend.
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
Xtest shape:  (100, 3, 32, 32)
ytest shape:  (100,)
/unsullied/sharefs/liangjiajun/workspace/research-2018/disentangle/A-Two-Step-Disentanglement-Method/DisAdvNet.py:111: UserWarning: Update your `Model` call to the Keras 2 API: `Model(outputs=[Elemwise{..., inputs=/input_1)`
  self.EncZ = Model(inputs = input_img, output=[z_mean,z_log_var])
/unsullied/sharefs/liangjiajun/workspace/research-2018/disentangle/A-Two-Step-Disentanglement-Method/DisAdvNet.py:69: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(16, kernel_initializer="glorot_normal")`
  h = Dense(dim,init=init)(inp)
building enc...
building dec...
building Sclsifier...
building Adv...
compile...
loading net...
net loaded
Traceback (most recent call last):
  File "test_net.py", line 75, in <module>
    z_m_test, z_std_test, s_test = net.predictEnc(x_test)
  File "/unsullied/sharefs/liangjiajun/workspace/research-2018/disentangle/A-Two-Step-Disentanglement-Method/DisAdvNet.py", line 232, in predictEnc
    s1 = self.EncS.predict(X1,batch_size=batch_size)
  File "/home/liangjiajun/.local/lib/python2.7/site-packages/keras/engine/training.py", line 1172, in predict
    steps=steps)
  File "/home/liangjiajun/.local/lib/python2.7/site-packages/keras/engine/training_arrays.py", line 297, in predict_loop
    batch_outs = f(ins_batch)
  File "/home/liangjiajun/.local/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 1277, in __call__
    return self.function(*inputs)
  File "/home/liangjiajun/.local/lib/python2.7/site-packages/theano/compile/function_module.py", line 917, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/liangjiajun/.local/lib/python2.7/site-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/liangjiajun/.local/lib/python2.7/site-packages/theano/compile/function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
ValueError: CorrMM images and kernel must have the same stack size

Apply node that caused the error: CorrMM{half, (2, 2), (1, 1), 1 False}(InplaceDimShuffle{0,3,1,2}.0, Subtensor{::, ::, ::int64, ::int64}.0)
Toposort index: 11
Inputs types: [TensorType(float32, 4D), TensorType(float32, 4D)]
Inputs shapes: [(100, 32, 3, 32), (5, 5, 64, 3)]
Inputs strides: [(12288, 4, 4096, 128), (768, 3840, -4, -256)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[Elemwise{Composite{(i0 * ((i1 + i2) + Abs((i1 + i2))))}}[(0, 1)](TensorConstant{(1, 1, 1, 1) of 0.5}, CorrMM{half, (2, 2), (1, 1), 1 False}.0, InplaceDimShuffle{x,0,x,x}.0)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "test_net.py", line 65, in <module>
    net = DisAdvNet.DisAdvNet(params,'','',False)
  File "/unsullied/sharefs/liangjiajun/workspace/research-2018/disentangle/A-Two-Step-Disentanglement-Method/DisAdvNet.py", line 115, in __init__
    x = add_conv_layer(input_img,n_features,filter_size,bn=encS_bn,actconv=act,stride=True,dilation=False,maxpool=False,upsamp = False,avgpool=False)
  File "/unsullied/sharefs/liangjiajun/workspace/research-2018/disentangle/A-Two-Step-Disentanglement-Method/DisAdvNet.py", line 83, in add_conv_layer
    h = Conv2D(n_features, kernel_size=(filter_size, filter_size),strides=(2,2), padding='same')(inp)
  File "/home/liangjiajun/.local/lib/python2.7/site-packages/keras/engine/base_layer.py", line 460, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/liangjiajun/.local/lib/python2.7/site-packages/keras/layers/convolutional.py", line 168, in call
    dilation_rate=self.dilation_rate)
  File "/home/liangjiajun/.local/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 2013, in conv2d
    filter_dilation=dilation_rate)

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

**Comment by devraj89** [comment]
@tracyliang18 I am facing the same issue. Did you manage to solve it? @naamahadad can you please help us with this.

**Comment by BERYLSHEEP** [comment]
I am facing the same issue too. Did anyone manage to solve it? @tracyliang18 @devraj89 @naamahadad can you please help us with this?

**Comment by devraj89** [comment]
@BERYLSHEEP I did not manage to solve it sadly.

**Comment by naamahadad** [comment]
@BERYLSHEEP Sorry but it eas too long ago and I don't have the data, maybe you can use this code:
https://github.com/QhelDIV/Two-Step-Disentanglement-Method
