### ISSUE TITLE
Dimension is not equal

### ISSUE THREAD

**Issue by BERYLSHEEP** [naamahadad/A-Two-Step-Disentanglement-Method#2]
While I am trying to run your code, i meet the error info as follows, I assume that something went wrong in the code and the provided weights demension, maybe not. Please give me some advises to solve it. Thank you!

[beryl@beryl-pc A-Two-Step-Disentanglement-Method-master]$ python test_net.py 
Using TensorFlow backend.
Xtest shape:  (100, 3, 32, 32)
ytest shape:  (100,)
building enc...
building dec...
building Sclsifier...
building Adv...
compile...
loading net...
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1628, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 0 in both shapes must be equal, but are 5 and 64. Shapes are [5,5,32,64] and [64,3,5,5]. for 'Assign' (op: 'Assign') with input shapes: [5,5,32,64], [64,3,5,5].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_net.py", line 72, in <module>
    net.Snet.load_weights(params['res_path']+'/'+params['mainnet']+'_'+data_type+'_weights.h5_Sfreeze_weights.h5')
  File "/usr/lib/python3.7/site-packages/keras/engine/saving.py", line 453, in load_wrapper
    return load_function(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/keras/engine/network.py", line 1211, in load_weights
    f, self.layers, reshape=reshape)
  File "/usr/lib/python3.7/site-packages/keras/engine/saving.py", line 1194, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "/usr/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 2715, in batch_set_value
    assign_op = x.assign(assign_placeholder)
  File "/usr/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 1718, in assign
    name=name)
  File "/usr/lib/python3.7/site-packages/tensorflow/python/ops/state_ops.py", line 221, in assign
    validate_shape=validate_shape)
  File "/usr/lib/python3.7/site-packages/tensorflow/python/ops/gen_state_ops.py", line 61, in assign
    use_locking=use_locking, name=name)
  File "/usr/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/usr/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1792, in __init__
    control_input_ops)
  File "/usr/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1631, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimension 0 in both shapes must be equal, but are 5 and 64. Shapes are [5,5,32,64] and [64,3,5,5]. for 'Assign' (op: 'Assign') with input shapes: [5,5,32,64], [64,3,5,5].

**Comment by biubiulsm** [comment]
Can you solve this issue? I met the same problem and I struggle for solving this for a while. Unluckily, I can solve such a problem. If you know, please tell me. Thanks a lot.
